export const ENV_KEYS = {
    EMAIL_SENDING_ACCOUNT: "EMAIL_SENDING_ACCOUNT",
    EMAIL_PASSWORD: "EMAIL_PASSWORD",
    EMAIL_TO_ACCESSIBILITY: "EMAIL_TO_ACCESSIBILITY",
    EMAIL_TO_CONTACT: "EMAIL_TO_CONTACT",
};